/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户登录 */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户登出 */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取仪表盘统计 */
        get: operations["getDashboardStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取告警趋势 */
        get: operations["getDashboardTrends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取资产列表 */
        get: operations["listAssets"];
        put?: never;
        /** 创建资产 */
        post: operations["createAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取资产详情 */
        get: operations["getAsset"];
        /** 更新资产 */
        put: operations["updateAsset"];
        post?: never;
        /** 删除资产 */
        delete: operations["deleteAsset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取告警列表 */
        get: operations["listAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取告警详情 */
        get: operations["getAlert"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 确认告警 */
        put: operations["acknowledgeAlert"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 解决告警 */
        put: operations["resolveAlert"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取告警统计 */
        get: operations["getAlertStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alert-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取告警规则列表 */
        get: operations["listAlertRules"];
        put?: never;
        /** 创建告警规则 */
        post: operations["createAlertRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alert-rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新告警规则 */
        put: operations["updateAlertRule"];
        post?: never;
        /** 删除告警规则 */
        delete: operations["deleteAlertRule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取机房列表 */
        get: operations["listSites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取机房详情 */
        get: operations["getSite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/racks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取机柜列表 */
        get: operations["listRacks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/racks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取机柜详情 */
        get: operations["getRack"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/racks/{id}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取机柜内设备 */
        get: operations["getRackDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取工单列表 */
        get: operations["listTickets"];
        put?: never;
        /** 创建工单 */
        post: operations["createTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取工单详情 */
        get: operations["getTicket"];
        /** 更新工单 */
        put: operations["updateTicket"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取用户列表 */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取用户详情 */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notification/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取通知渠道列表 */
        get: operations["listChannels"];
        put?: never;
        /** 创建通知渠道 */
        post: operations["createChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notification/channels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新通知渠道 */
        put: operations["updateChannel"];
        post?: never;
        /** 删除通知渠道 */
        delete: operations["deleteChannel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notification/channels/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 测试通知渠道 */
        post: operations["testChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnostics/assets/{id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取资产时间线（用于故障诊断）
         * @description 聚合 alerts / tickets / assets / asset_networks 四张表，按时间倒序返回事件流。
         *     含 MTTR (平均恢复时间)、open_alerts、open_tickets 等摘要。
         */
        get: operations["getAssetTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alert-suppressions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出告警抑制规则 */
        get: operations["listAlertSuppressions"];
        put?: never;
        /** 创建告警抑制规则 */
        post: operations["createAlertSuppression"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alert-suppressions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 获取单条告警抑制规则 */
        get: operations["getAlertSuppression"];
        /** 更新告警抑制规则 */
        put: operations["updateAlertSuppression"];
        post?: never;
        /** 删除告警抑制规则 */
        delete: operations["deleteAlertSuppression"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alert-suppressions/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 模拟评估一条告警是否被抑制 */
        post: operations["previewSuppression"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取网络拓扑图
         * @description 聚合 assets + asset_networks + alerts，自动布局 (环形) + 虚拟节点标记
         */
        get: operations["getTopology"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TimelineEvent: {
            /** Format: date-time */
            ts?: string;
            /** @enum {string} */
            kind?: "alert" | "ticket" | "status_change" | "link_change";
            sub_kind?: string;
            severity?: number;
            title?: string;
            description?: string;
            /** Format: uuid */
            ref_id?: string;
            ref_table?: string;
        };
        DiagnosticAsset: {
            /** Format: uuid */
            id?: string;
            name?: string;
            asset_tag?: string;
            asset_type?: string;
            brand?: string;
            model?: string;
            status?: string;
            /** Format: uuid */
            site_id?: string;
            site_name?: string;
            /** Format: uuid */
            rack_id?: string;
            rack_name?: string;
        };
        DiagnosticSummary: {
            alert_count?: number;
            ticket_count?: number;
            open_alerts?: number;
            open_tickets?: number;
            /** Format: date-time */
            last_offline?: string;
            /** Format: date-time */
            last_online?: string;
            mttr_seconds?: number | null;
            link_down_count?: number;
            window_days?: number;
            /** Format: date-time */
            window_start?: string;
            /** Format: date-time */
            window_end?: string;
            /** Format: uuid */
            asset_id?: string;
        };
        DiagnosticTimeline: {
            asset?: components["schemas"]["DiagnosticAsset"];
            events?: components["schemas"]["TimelineEvent"][];
            summary?: components["schemas"]["DiagnosticSummary"];
        };
        AlertSuppression: {
            /** Format: uuid */
            id?: string;
            name?: string;
            severity_max?: number;
            host_pattern?: string;
            time_window_seconds?: number;
            ttl_seconds?: number;
            enabled?: boolean;
            description?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        SuppressionMatchResult: {
            suppressed?: boolean;
            /** Format: uuid */
            matched_rule?: string;
            reason?: string;
            /** Format: date-time */
            last_fired_at?: string;
            /** Format: date-time */
            window_expires_at?: string;
        };
        TopologyNode: {
            /** Format: uuid */
            id?: string;
            name?: string;
            asset_tag?: string;
            asset_type?: string;
            brand?: string;
            status?: string;
            open_alerts?: number;
            is_virtual?: boolean;
            connected_assets?: number;
            position_x?: number;
            position_y?: number;
        };
        TopologyEdge: {
            /** Format: uuid */
            id?: string;
            source?: string;
            target?: string;
            interface_name?: string;
            status?: string;
            speed?: number;
            purpose?: string;
        };
        TopologyStats: {
            total_nodes?: number;
            total_edges?: number;
            nodes_with_alert?: number;
            down_edges?: number;
            virtual_nodes?: number;
            window_days?: number;
        };
        TopologyGraph: {
            nodes?: components["schemas"]["TopologyNode"][];
            edges?: components["schemas"]["TopologyEdge"][];
            stats?: components["schemas"]["TopologyStats"];
            /** Format: date-time */
            generated_at?: string;
        };
        Error: {
            code?: number;
            message?: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResponse: {
            /** @example 0 */
            code?: number;
            data?: {
                token?: string;
                user?: components["schemas"]["User"];
            };
        };
        DashboardStats: {
            code?: number;
            data?: {
                assets?: number;
                alerts?: number;
                tickets?: number;
                sites?: number;
                machines?: number;
                networks?: number;
            };
        };
        DashboardTrends: {
            code?: number;
            data?: {
                alert_trends?: {
                    date?: string;
                    count?: number;
                }[];
            };
        };
        Asset: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @enum {string} */
            asset_type?: "server" | "switch" | "router" | "firewall" | "storage" | "other";
            ip_address?: string;
            mac_address?: string;
            /** @enum {string} */
            status?: "active" | "inactive" | "maintenance";
            /** Format: uuid */
            site_id?: string;
            site_name?: string;
            /** Format: uuid */
            rack_id?: string;
            rack_name?: string;
            rack_position?: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        AssetInput: {
            name: string;
            asset_type: string;
            ip_address: string;
            mac_address?: string;
            /** Format: uuid */
            site_id?: string;
            /** Format: uuid */
            rack_id?: string;
            rack_position?: number;
        };
        AssetList: {
            code?: number;
            data?: {
                items?: components["schemas"]["Asset"][];
                total?: number;
                page?: number;
                page_size?: number;
            };
        };
        Alert: {
            /** Format: uuid */
            id?: string;
            host?: string;
            message?: string;
            severity?: number;
            severity_name?: string;
            /** @enum {string} */
            status?: "problem" | "acknowledged" | "resolved";
            /** Format: uuid */
            asset_id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            ack_time?: string;
            ack_user?: string;
            /** Format: date-time */
            resolve_time?: string;
            resolve_user?: string;
            duration?: number;
        };
        AlertList: {
            code?: number;
            data?: {
                items?: components["schemas"]["Alert"][];
                stats?: {
                    total?: number;
                    problem?: number;
                    acknowledged?: number;
                    resolved?: number;
                };
            };
        };
        AlertStats: {
            code?: number;
            data?: {
                by_severity?: {
                    severity?: number;
                    severity_name?: string;
                    count?: number;
                }[];
                by_hour?: {
                    /** Format: date-time */
                    hour?: string;
                    count?: number;
                }[];
            };
        };
        AlertRule: {
            /** Format: uuid */
            id?: string;
            name?: string;
            condition?: string;
            threshold?: number;
            severity?: number;
            is_enabled?: boolean;
            notification_channels?: string[];
        };
        AlertRuleInput: {
            name: string;
            condition: string;
            threshold: number;
            severity: number;
            is_enabled?: boolean;
        };
        AlertRuleList: {
            code?: number;
            data?: components["schemas"]["AlertRule"][];
        };
        Site: {
            /** Format: uuid */
            id?: string;
            name?: string;
            location?: string;
            is_active?: boolean;
        };
        SiteList: {
            code?: number;
            data?: components["schemas"]["Site"][];
        };
        SiteDetail: {
            code?: number;
            data?: {
                site?: components["schemas"]["Site"];
                rack_count?: number;
                asset_count?: number;
            };
        };
        Rack: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: uuid */
            site_id?: string;
            total_units?: number;
            used_units?: number;
        };
        RackList: {
            code?: number;
            data?: components["schemas"]["Rack"][];
        };
        RackDevice: components["schemas"]["Asset"] & {
            /** @enum {string} */
            status?: "green" | "yellow" | "red";
            alert_count?: number;
        };
        RackDeviceList: {
            code?: number;
            data?: components["schemas"]["RackDevice"][];
        };
        Ticket: {
            id?: string;
            title?: string;
            description?: string;
            /** @enum {string} */
            priority?: "critical" | "high" | "normal" | "low";
            /** @enum {string} */
            status?: "open" | "in_progress" | "pending" | "resolved" | "closed";
            requester?: string;
            assignee?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        TicketInput: {
            title: string;
            description?: string;
            priority: string;
        };
        TicketList: {
            code?: number;
            data?: components["schemas"]["Ticket"][];
        };
        User: {
            /** Format: uuid */
            id?: string;
            username?: string;
            nickname?: string;
            email?: string;
            /** @enum {string} */
            role?: "admin" | "operator" | "viewer";
            /** Format: date-time */
            created_at?: string;
        };
        UserList: {
            code?: number;
            data?: components["schemas"]["User"][];
        };
        NotificationChannel: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @enum {string} */
            type?: "email" | "dingtalk" | "wechat" | "webhook";
            config?: Record<string, never>;
            is_enabled?: boolean;
        };
        ChannelInput: {
            name: string;
            type: string;
            config?: Record<string, never>;
        };
        ChannelList: {
            code?: number;
            data?: components["schemas"]["NotificationChannel"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 用户名 */
                    username: string;
                    /** @description 密码 */
                    password: string;
                };
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 登出成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDashboardStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStats"];
                };
            };
        };
    };
    getDashboardTrends: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardTrends"];
                };
            };
        };
    };
    listAssets: {
        parameters: {
            query?: {
                site_id?: string;
                type?: string;
                status?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetList"];
                };
            };
        };
    };
    createAsset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetInput"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
        };
    };
    getAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
        };
    };
    updateAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetInput"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
        };
    };
    deleteAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAlerts: {
        parameters: {
            query?: {
                status?: "problem" | "acknowledged" | "resolved";
                severity?: number;
                host_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertList"];
                };
            };
        };
    };
    getAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
        };
    };
    acknowledgeAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 确认成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resolveAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 解决成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAlertStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertStats"];
                };
            };
        };
    };
    listAlertRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleList"];
                };
            };
        };
    };
    createAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleInput"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleInput"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteList"];
                };
            };
        };
    };
    getSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteDetail"];
                };
            };
        };
    };
    listRacks: {
        parameters: {
            query?: {
                site_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RackList"];
                };
            };
        };
    };
    getRack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rack"];
                };
            };
        };
    };
    getRackDevices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RackDeviceList"];
                };
            };
        };
    };
    listTickets: {
        parameters: {
            query?: {
                status?: string;
                priority?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketList"];
                };
            };
        };
    };
    createTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketInput"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
        };
    };
    updateTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketInput"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    listChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelList"];
                };
            };
        };
    };
    createChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelInput"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelInput"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    testChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 测试消息已发送 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAssetTimeline: {
        parameters: {
            query?: {
                /** @description 查询窗口（天）默认 30，最大 365 */
                days?: number;
                /** @description 事件数上限，默认 200，最大 1000 */
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticTimeline"];
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 资产不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAlertSuppressions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertSuppression"][];
                };
            };
        };
    };
    createAlertSuppression: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertSuppression"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertSuppression"];
                };
            };
            /** @description 参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAlertSuppression: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertSuppression"];
                };
            };
            /** @description 不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAlertSuppression: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertSuppression"];
                };
            };
            /** @description 参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAlertSuppression: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    previewSuppression: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    severity: number;
                    /** Format: uuid */
                    host_id: string;
                    host_name: string;
                };
            };
        };
        responses: {
            /** @description 评估结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuppressionMatchResult"];
                };
            };
        };
    };
    getTopology: {
        parameters: {
            query?: {
                days?: number;
                only_with_alerts?: boolean;
                /** @description 逗号分隔，如 "server,switch" */
                asset_types?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologyGraph"];
                };
            };
        };
    };
}
