/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户登录 */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户登出 */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/skip-password-change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 确认无强制改密待办 (幂等)
         * @description C7: 用户在 `/change-password` 页点"跳过"时调用。
         *
         *     判据是服务端的 `users.must_change_password`，**不看请求体的 reason**（客户端可伪造）：
         *     - `must_change_password=true` → 400（主人 7/02 决策：首次登录 / 管理员重置后的强制改密不可跳）
         *     - `must_change_password=false` → 200，幂等且**不写任何状态**（不再写 password_set_at）
         *
         *     修复前只拒绝 `reason=="first_login"` 字面量，空 body 或 `reason=optional` 即可清 flag
         *     绕过强改密（见 docs/FIX-PLAN-AUTHZ-LEFTOVER.md S-1）。
         */
        post: operations["skipPasswordChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取仪表盘统计 */
        get: operations["getDashboardStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取告警趋势 */
        get: operations["getDashboardTrends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取关键 KPI 指标
         * @description 返回 MTTR (平均恢复时间)、MTTD (平均检测时间)、告警密度、SLA 达成率。
         *     days 默认 7，范围 1-90。
         */
        get: operations["getKPIs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取资产列表 */
        get: operations["listAssets"];
        put?: never;
        /** 创建资产 */
        post: operations["createAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取资产详情 */
        get: operations["getAsset"];
        /** 更新资产 */
        put: operations["updateAsset"];
        post?: never;
        /** 删除资产 */
        delete: operations["deleteAsset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取告警列表 */
        get: operations["listAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取告警详情 */
        get: operations["getAlert"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 确认告警 */
        put: operations["acknowledgeAlert"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 解决告警 */
        put: operations["resolveAlert"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{id}/mark-fp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 标记/反标记告警为误报 */
        post: operations["markFalsePositive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/false-positives/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 导出误报训练集 CSV */
        get: operations["exportFalsePositives"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取告警统计 */
        get: operations["getAlertStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alert-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取告警规则列表 */
        get: operations["listAlertRules"];
        put?: never;
        /** 创建告警规则 */
        post: operations["createAlertRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alert-rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新告警规则 */
        put: operations["updateAlertRule"];
        post?: never;
        /** 删除告警规则 */
        delete: operations["deleteAlertRule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取机房列表 */
        get: operations["listSites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取机房详情 */
        get: operations["getSite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/racks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取机柜列表 */
        get: operations["listRacks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/racks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取机柜详情 */
        get: operations["getRack"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/racks/{id}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取机柜内设备 */
        get: operations["getRackDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取工单列表 */
        get: operations["listTickets"];
        put?: never;
        /** 创建工单 */
        post: operations["createTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取工单详情 */
        get: operations["getTicket"];
        /** 更新工单 */
        put: operations["updateTicket"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取用户列表 */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取用户详情 */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notification-channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取通知渠道列表 */
        get: operations["listChannels"];
        put?: never;
        /** 创建通知渠道 */
        post: operations["createChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notification-channels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新通知渠道 */
        put: operations["updateChannel"];
        post?: never;
        /** 删除通知渠道 */
        delete: operations["deleteChannel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notification-channels/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 测试通知渠道 */
        put: operations["testChannel"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnostics/assets/{id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取资产时间线（用于故障诊断）
         * @description 聚合 alerts / tickets / assets / asset_networks 四张表，按时间倒序返回事件流。
         *     含 MTTR (平均恢复时间)、open_alerts、open_tickets 等摘要。
         */
        get: operations["getAssetTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnostics/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 资产 ICMP ping 探活
         * @description 调用系统 ping 工具探测资产 IP 的可达性。
         *     count 默认 4，上限 20。响应包含 transmitted/received/loss/min/avg/max ms。
         */
        get: operations["pingAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnostics/traceroute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 资产 traceroute 网络路径
         * @description 调用系统 traceroute 跟踪资产 IP 的网络路径。
         *     maxHops 默认 30，上限 64。
         */
        get: operations["tracerouteAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/postmortem/assets/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 下载资产复盘 PDF 报告
         * @description 聚合 alerts / tickets / status 历史生成 1-2 页 PDF 复盘报告。
         *     报告含：资产概要、可靠性指标（MTTR/告警密度）、事件时间线、Top 5 告警。
         *     days 默认 30，上限 365。
         */
        get: operations["downloadPostmortemReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alert-suppressions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出告警抑制规则 */
        get: operations["listAlertSuppressions"];
        put?: never;
        /** 创建告警抑制规则 */
        post: operations["createAlertSuppression"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alert-suppressions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 获取单条告警抑制规则 */
        get: operations["getAlertSuppression"];
        /** 更新告警抑制规则 */
        put: operations["updateAlertSuppression"];
        post?: never;
        /** 删除告警抑制规则 */
        delete: operations["deleteAlertSuppression"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alert-suppressions/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 模拟评估一条告警是否被抑制 */
        post: operations["previewSuppression"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取网络拓扑图
         * @description 聚合 assets + asset_networks + alerts，自动布局 (环形) + 虚拟节点标记
         */
        get: operations["getTopology"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oncall/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前在班的 user */
        get: operations["getCurrentOncall"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oncall/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出值班组 */
        get: operations["listOncallSchedules"];
        put?: never;
        /** 创建值班组 */
        post: operations["createOncallSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oncall/schedules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除值班组（级联删 shifts） */
        delete: operations["deleteOncallSchedule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oncall/schedules/{id}/shifts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 列出 schedule 下所有班次 */
        get: operations["listOncallShifts"];
        put?: never;
        /** 创建班次 */
        post: operations["createOncallShift"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oncall/shifts/{shift_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shift_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除班次 */
        delete: operations["deleteOncallShift"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oncall/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出升级策略 */
        get: operations["listEscalationPolicies"];
        put?: never;
        /** 创建升级策略（含 levels） */
        post: operations["createEscalationPolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oncall/policies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 获取单条升级策略 */
        get: operations["getEscalationPolicy"];
        put?: never;
        post?: never;
        /** 删除升级策略 */
        delete: operations["deleteEscalationPolicy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runbooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出 Runbook */
        get: operations["listRunbooks"];
        put?: never;
        /** 创建 Runbook */
        post: operations["createRunbook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runbooks/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 按告警推荐 Runbook */
        get: operations["recommendRunbooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runbooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 获取 Runbook */
        get: operations["getRunbook"];
        /** 更新 Runbook */
        put: operations["updateRunbook"];
        post?: never;
        /** 删除 Runbook */
        delete: operations["deleteRunbook"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metric-snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 时序查询 */
        get: operations["queryMetricSnapshots"];
        put?: never;
        /** 批量插入 */
        post: operations["bulkInsertMetricSnapshots"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metric-snapshots/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取 asset+key 最新 N 个点 */
        get: operations["latestMetricSnapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TimelineEvent: {
            /** Format: date-time */
            ts?: string;
            /** @enum {string} */
            kind?: "alert" | "ticket" | "status_change" | "link_change";
            sub_kind?: string;
            severity?: number;
            title?: string;
            description?: string;
            /** Format: uuid */
            ref_id?: string;
            ref_table?: string;
        };
        DiagnosticAsset: {
            /** Format: uuid */
            id?: string;
            name?: string;
            asset_tag?: string;
            asset_type?: string;
            brand?: string;
            model?: string;
            status?: string;
            /** Format: uuid */
            site_id?: string;
            site_name?: string;
            /** Format: uuid */
            rack_id?: string;
            rack_name?: string;
        };
        DiagnosticSummary: {
            alert_count?: number;
            ticket_count?: number;
            open_alerts?: number;
            open_tickets?: number;
            /** Format: date-time */
            last_offline?: string;
            /** Format: date-time */
            last_online?: string;
            mttr_seconds?: number | null;
            link_down_count?: number;
            window_days?: number;
            /** Format: date-time */
            window_start?: string;
            /** Format: date-time */
            window_end?: string;
            /** Format: uuid */
            asset_id?: string;
        };
        DiagnosticTimeline: {
            asset?: components["schemas"]["DiagnosticAsset"];
            events?: components["schemas"]["TimelineEvent"][];
            summary?: components["schemas"]["DiagnosticSummary"];
        };
        PingResult: {
            host?: string;
            count?: number;
            transmitted?: number;
            received?: number;
            loss_percent?: number;
            min_ms?: number;
            avg_ms?: number;
            max_ms?: number;
            stddev_ms?: number;
            /** Format: int64 */
            duration_ms?: number;
        };
        TracerouteResult: {
            host?: string;
            max_hops?: number;
            reached?: boolean;
            /** Format: int64 */
            duration_ms?: number;
            hops?: components["schemas"]["TracerouteHop"][];
        };
        TracerouteHop: {
            hop?: number;
            host?: string;
            ip?: string;
            rtts?: string[];
            lossed?: boolean;
        };
        AlertSuppression: {
            /** Format: uuid */
            id?: string;
            name?: string;
            severity_max?: number;
            host_pattern?: string;
            time_window_seconds?: number;
            ttl_seconds?: number;
            enabled?: boolean;
            description?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        SuppressionMatchResult: {
            suppressed?: boolean;
            /** Format: uuid */
            matched_rule?: string;
            reason?: string;
            /** Format: date-time */
            last_fired_at?: string;
            /** Format: date-time */
            window_expires_at?: string;
        };
        TopologyNode: {
            /** Format: uuid */
            id?: string;
            name?: string;
            asset_tag?: string;
            asset_type?: string;
            brand?: string;
            status?: string;
            open_alerts?: number;
            is_virtual?: boolean;
            connected_assets?: number;
            position_x?: number;
            position_y?: number;
        };
        TopologyEdge: {
            /** Format: uuid */
            id?: string;
            source?: string;
            target?: string;
            interface_name?: string;
            status?: string;
            speed?: number;
            purpose?: string;
        };
        TopologyStats: {
            total_nodes?: number;
            total_edges?: number;
            nodes_with_alert?: number;
            down_edges?: number;
            virtual_nodes?: number;
            window_days?: number;
        };
        TopologyGraph: {
            nodes?: components["schemas"]["TopologyNode"][];
            edges?: components["schemas"]["TopologyEdge"][];
            stats?: components["schemas"]["TopologyStats"];
            /** Format: date-time */
            generated_at?: string;
        };
        OncallSchedule: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string;
            timezone?: string;
            enabled?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        OncallShift: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            schedule_id?: string;
            /** Format: uuid */
            user_id?: string;
            user_name?: string;
            /** Format: date-time */
            starts_at?: string;
            /** Format: date-time */
            ends_at?: string;
            /** Format: date-time */
            created_at?: string;
        };
        OncallCurrent: {
            /** Format: uuid */
            schedule_id?: string;
            schedule_name?: string;
            /** Format: uuid */
            user_id?: string;
            user_name?: string;
            /** Format: date-time */
            starts_at?: string;
            /** Format: date-time */
            ends_at?: string;
            /** Format: uuid */
            shift_id?: string;
        };
        EscalationLevel: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            policy_id?: string;
            level?: number;
            target_type?: string;
            target_id?: string;
            wait_minutes?: number;
            notify_methods?: string;
        };
        EscalationPolicy: {
            /** Format: uuid */
            id?: string;
            name?: string;
            enabled?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            levels?: components["schemas"]["EscalationLevel"][];
        };
        Error: {
            code?: number;
            message?: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResponse: {
            /** @example 0 */
            code?: number;
            data?: {
                token?: string;
                user?: components["schemas"]["User"];
                /** @example false */
                must_change_password?: boolean;
            };
        };
        DashboardStats: {
            code?: number;
            data?: {
                assets?: number;
                alerts?: number;
                tickets?: number;
                sites?: number;
                machines?: number;
                networks?: number;
            };
        };
        DashboardTrends: {
            code?: number;
            data?: {
                alert_trends?: {
                    date?: string;
                    count?: number;
                }[];
            };
        };
        KPI: {
            /**
             * Format: int64
             * @description 平均恢复时间（秒），无已解决告警时为 null
             */
            mttr_seconds?: number | null;
            /**
             * Format: int64
             * @description 平均检测时间（秒），无已确认告警时为 null
             */
            mttd_seconds?: number | null;
            /** @description 窗口内每日告警数（alerts/day） */
            alert_density?: number;
            /** @description SLA 达成率（已关单中按时比例，0-1），无已关工单时为 null */
            sla_closed_rate?: number | null;
            window_days?: number;
            /** Format: date-time */
            window_start?: string;
            /** Format: date-time */
            window_end?: string;
            /** Format: int64 */
            resolved_alerts?: number;
            /** Format: int64 */
            acked_alerts?: number;
            /** Format: int64 */
            closed_tickets?: number;
            /** Format: int64 */
            on_time_tickets?: number;
        };
        Asset: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @enum {string} */
            asset_type?: "server" | "switch" | "router" | "firewall" | "storage" | "other";
            ip_address?: string;
            mac_address?: string;
            /** @enum {string} */
            status?: "active" | "inactive" | "maintenance";
            /** Format: uuid */
            site_id?: string;
            site_name?: string;
            /** Format: uuid */
            rack_id?: string;
            rack_name?: string;
            rack_position?: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        AssetInput: {
            name: string;
            asset_type: string;
            ip_address: string;
            mac_address?: string;
            /** Format: uuid */
            site_id?: string;
            /** Format: uuid */
            rack_id?: string;
            rack_position?: number;
        };
        AssetList: {
            code?: number;
            data?: {
                items?: components["schemas"]["Asset"][];
                total?: number;
                page?: number;
                page_size?: number;
            };
        };
        Alert: {
            /** Format: uuid */
            id?: string;
            host?: string;
            message?: string;
            severity?: number;
            severity_name?: string;
            /** @enum {string} */
            status?: "problem" | "acknowledged" | "resolved";
            /** Format: uuid */
            asset_id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            ack_time?: string;
            ack_user?: string;
            /** Format: date-time */
            resolve_time?: string;
            resolve_user?: string;
            duration?: number;
            /** @description 是否被标记为误报（小改进 */
            is_false_positive?: boolean;
            /** @description 标记人 username */
            marked_by?: string;
            /** Format: date-time */
            marked_at?: string;
            /** @description 误报标记备注 */
            false_positive_note?: string;
        };
        AlertList: {
            code?: number;
            data?: {
                items?: components["schemas"]["Alert"][];
                stats?: {
                    total?: number;
                    problem?: number;
                    acknowledged?: number;
                    resolved?: number;
                };
                /** @description 还有下一页时返回（items 长度等于 limit 时） */
                next_cursor?: string;
            };
        };
        AlertStats: {
            code?: number;
            data?: {
                by_severity?: {
                    severity?: number;
                    severity_name?: string;
                    count?: number;
                }[];
                by_hour?: {
                    /** Format: date-time */
                    hour?: string;
                    count?: number;
                }[];
            };
        };
        AlertRule: {
            /** Format: uuid */
            id?: string;
            name?: string;
            condition?: string;
            threshold?: number;
            severity?: number;
            is_enabled?: boolean;
            notification_channels?: string[];
        };
        AlertRuleInput: {
            name: string;
            condition: string;
            threshold: number;
            severity: number;
            is_enabled?: boolean;
        };
        AlertRuleList: {
            code?: number;
            data?: components["schemas"]["AlertRule"][];
        };
        Site: {
            /** Format: uuid */
            id?: string;
            name?: string;
            location?: string;
            is_active?: boolean;
        };
        SiteList: {
            code?: number;
            data?: components["schemas"]["Site"][];
        };
        SiteDetail: {
            code?: number;
            data?: {
                site?: components["schemas"]["Site"];
                rack_count?: number;
                asset_count?: number;
            };
        };
        Rack: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: uuid */
            site_id?: string;
            total_units?: number;
            used_units?: number;
        };
        RackList: {
            code?: number;
            data?: components["schemas"]["Rack"][];
        };
        RackDevice: components["schemas"]["Asset"] & {
            /** @enum {string} */
            status?: "green" | "yellow" | "red";
            alert_count?: number;
        };
        RackDeviceList: {
            code?: number;
            data?: components["schemas"]["RackDevice"][];
        };
        Ticket: {
            id?: string;
            title?: string;
            description?: string;
            /** @enum {string} */
            priority?: "critical" | "high" | "normal" | "low";
            /** @enum {string} */
            status?: "open" | "in_progress" | "pending" | "resolved" | "closed";
            requester?: string;
            assignee?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        TicketInput: {
            title: string;
            description?: string;
            priority: string;
        };
        TicketList: {
            code?: number;
            data?: components["schemas"]["Ticket"][];
        };
        User: {
            /** Format: uuid */
            id?: string;
            username?: string;
            nickname?: string;
            email?: string;
            /** @enum {string} */
            role?: "admin" | "ops_admin" | "ops_user" | "auditor" | "readonly" | "user";
            /** Format: date-time */
            created_at?: string;
        };
        UserList: {
            code?: number;
            data?: components["schemas"]["User"][];
        };
        NotificationChannel: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /**
             * @description 响应模型
             * @enum {string}
             */
            type?: "email" | "dingtalk" | "wechat" | "webhook";
            /** @description JSON 字符串，键名见 internal/notification/channelConfig 的 json tag */
            config?: string;
            is_enabled?: boolean;
        };
        ChannelInput: {
            name: string;
            /**
             * @description wechat = 企业微信群机器人（config 只需 url，回执 errcode 判失败）
             * @enum {string}
             */
            type: "email" | "dingtalk" | "wechat" | "webhook";
            /** @description JSON 字符串，键名见 internal/notification/channelConfig 的 json tag */
            config?: string;
            /** @description 省略时后端按 true 处理（新建） */
            is_enabled?: boolean;
        };
        ChannelList: {
            code?: number;
            data?: components["schemas"]["NotificationChannel"][];
        };
        Runbook: {
            /** Format: uuid */
            id?: string;
            title?: string;
            asset_type?: string;
            summary?: string;
            content_md?: string;
            /** @description JSON 步骤数组 */
            steps?: string;
            tags?: string;
            /** @description 0=不限制; 1-5=对应告警严重度 */
            severity?: number;
            enabled?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        MetricSnapshot: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            asset_id?: string;
            key?: string;
            /** Format: double */
            value?: number;
            /** Format: date-time */
            ts?: string;
            /** Format: date-time */
            created_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 用户名 */
                    username: string;
                    /** @description 密码 */
                    password: string;
                };
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 登出成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    skipPasswordChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @deprecated
                     * @description 已废弃：服务端不再读取，保留仅为兼容既有客户端请求体
                     * @example optional
                     */
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description 当前无强制改密待办 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 0 */
                        code?: number;
                        /** @example 当前无需改密 */
                        message?: string;
                    };
                };
            };
            /** @description 当前账号处于强制改密状态, 不允许跳过 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDashboardStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStats"];
                };
            };
        };
    };
    getDashboardTrends: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardTrends"];
                };
            };
        };
    };
    getKPIs: {
        parameters: {
            query?: {
                /** @description 窗口天数，默认 7，范围 1-90 */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KPI"];
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAssets: {
        parameters: {
            query?: {
                site_id?: string;
                type?: string;
                status?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetList"];
                };
            };
        };
    };
    createAsset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetInput"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
        };
    };
    getAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
        };
    };
    updateAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetInput"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
        };
    };
    deleteAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAlerts: {
        parameters: {
            query?: {
                status?: "problem" | "acknowledged" | "resolved";
                severity?: number;
                host_id?: string;
                /** @description 返回条数上限，默认 100，上限 1000 */
                limit?: number;
                /** @description v2.0 游标分页，取上一页响应的 next_cursor；解码失败时降级为忽略 */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertList"];
                };
            };
        };
    };
    getAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
        };
    };
    acknowledgeAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 确认成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resolveAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 解决成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    markFalsePositive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description true=标记为误报，false=反标记 */
                    is_false_positive: boolean;
                    /** @description 误报备注（如"周期性抖动"） */
                    note?: string;
                };
            };
        };
        responses: {
            /** @description 操作成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            /** @description 告警不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exportFalsePositives: {
        parameters: {
            query?: {
                /** @description 可选 RFC3339 时间，增量导出 marked_at >= since 的记录 */
                since?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV 文件流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
        };
    };
    getAlertStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertStats"];
                };
            };
        };
    };
    listAlertRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleList"];
                };
            };
        };
    };
    createAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleInput"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleInput"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteList"];
                };
            };
        };
    };
    getSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteDetail"];
                };
            };
        };
    };
    listRacks: {
        parameters: {
            query?: {
                site_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RackList"];
                };
            };
        };
    };
    getRack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rack"];
                };
            };
        };
    };
    getRackDevices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RackDeviceList"];
                };
            };
        };
    };
    listTickets: {
        parameters: {
            query?: {
                status?: string;
                priority?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketList"];
                };
            };
        };
    };
    createTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketInput"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
        };
    };
    updateTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketInput"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    listChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelList"];
                };
            };
        };
    };
    createChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelInput"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelInput"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    testChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 测试消息已发送 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAssetTimeline: {
        parameters: {
            query?: {
                /** @description 查询窗口（天）默认 30，最大 365 */
                days?: number;
                /** @description 事件数上限，默认 200，最大 1000 */
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticTimeline"];
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 资产不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pingAsset: {
        parameters: {
            query: {
                /** @description 目标 host（IP 或 hostname） */
                host: string;
                /** @description ping 次数，默认 4，上限 20 */
                count?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingResult"];
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ping 执行失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tracerouteAsset: {
        parameters: {
            query: {
                /** @description 目标 host（IP 或 hostname） */
                host: string;
                /** @description 最大跳数，默认 30，上限 64 */
                maxHops?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TracerouteResult"];
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description traceroute 执行失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    downloadPostmortemReport: {
        parameters: {
            query?: {
                /** @description 查询窗口（天）默认 30，最大 365 */
                days?: number;
                /** @description 事件数上限，默认 200，最大 1000 */
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF 文件流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 资产不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 报告生成失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAlertSuppressions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertSuppression"][];
                };
            };
        };
    };
    createAlertSuppression: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertSuppression"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertSuppression"];
                };
            };
            /** @description 参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAlertSuppression: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertSuppression"];
                };
            };
            /** @description 不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAlertSuppression: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertSuppression"];
                };
            };
            /** @description 参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAlertSuppression: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    previewSuppression: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    severity: number;
                    /** Format: uuid */
                    host_id: string;
                    host_name: string;
                };
            };
        };
        responses: {
            /** @description 评估结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuppressionMatchResult"];
                };
            };
        };
    };
    getTopology: {
        parameters: {
            query?: {
                days?: number;
                only_with_alerts?: boolean;
                /** @description 逗号分隔，如 "server,switch" */
                asset_types?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologyGraph"];
                };
            };
        };
    };
    getCurrentOncall: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OncallCurrent"][];
                };
            };
        };
    };
    listOncallSchedules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createOncallSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OncallSchedule"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteOncallSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listOncallShifts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createOncallShift: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OncallShift"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteOncallShift: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shift_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listEscalationPolicies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalationPolicy"][];
                };
            };
        };
    };
    createEscalationPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EscalationPolicy"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getEscalationPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalationPolicy"];
                };
            };
        };
    };
    deleteEscalationPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRunbooks: {
        parameters: {
            query?: {
                asset_type?: string;
                severity?: number;
                enabled?: boolean;
                keyword?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Runbook"][];
                        total?: number;
                    };
                };
            };
        };
    };
    createRunbook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Runbook"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Runbook"];
                };
            };
            /** @description 参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    recommendRunbooks: {
        parameters: {
            query?: {
                asset_type?: string;
                severity?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 推荐列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Runbook"][];
                };
            };
        };
    };
    getRunbook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Runbook"];
                };
            };
            /** @description 不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateRunbook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Runbook"];
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteRunbook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    queryMetricSnapshots: {
        parameters: {
            query?: {
                asset_id?: string;
                key?: string;
                from?: string;
                to?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricSnapshot"][];
                };
            };
        };
    };
    bulkInsertMetricSnapshots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetricSnapshot"][];
            };
        };
        responses: {
            /** @description 插入成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    latestMetricSnapshots: {
        parameters: {
            query: {
                asset_id: string;
                key: string;
                n?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricSnapshot"][];
                };
            };
        };
    };
}
