// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/alert/v1/alert.proto

package alertv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Alert severity (mirrors internal/model)
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_INFO        Severity = 1
	Severity_SEVERITY_WARNING     Severity = 2
	Severity_SEVERITY_ERROR       Severity = 3
	Severity_SEVERITY_CRITICAL    Severity = 4
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_INFO",
		2: "SEVERITY_WARNING",
		3: "SEVERITY_ERROR",
		4: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_INFO":        1,
		"SEVERITY_WARNING":     2,
		"SEVERITY_ERROR":       3,
		"SEVERITY_CRITICAL":    4,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_alert_v1_alert_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_api_proto_alert_v1_alert_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_alert_v1_alert_proto_rawDescGZIP(), []int{0}
}

type AlertStatus int32

const (
	AlertStatus_ALERT_STATUS_UNSPECIFIED AlertStatus = 0
	AlertStatus_ALERT_STATUS_PENDING     AlertStatus = 1
	AlertStatus_ALERT_STATUS_ACKED       AlertStatus = 2
	AlertStatus_ALERT_STATUS_RESOLVED    AlertStatus = 3
)

// Enum value maps for AlertStatus.
var (
	AlertStatus_name = map[int32]string{
		0: "ALERT_STATUS_UNSPECIFIED",
		1: "ALERT_STATUS_PENDING",
		2: "ALERT_STATUS_ACKED",
		3: "ALERT_STATUS_RESOLVED",
	}
	AlertStatus_value = map[string]int32{
		"ALERT_STATUS_UNSPECIFIED": 0,
		"ALERT_STATUS_PENDING":     1,
		"ALERT_STATUS_ACKED":       2,
		"ALERT_STATUS_RESOLVED":    3,
	}
)

func (x AlertStatus) Enum() *AlertStatus {
	p := new(AlertStatus)
	*p = x
	return p
}

func (x AlertStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_alert_v1_alert_proto_enumTypes[1].Descriptor()
}

func (AlertStatus) Type() protoreflect.EnumType {
	return &file_api_proto_alert_v1_alert_proto_enumTypes[1]
}

func (x AlertStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertStatus.Descriptor instead.
func (AlertStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_alert_v1_alert_proto_rawDescGZIP(), []int{1}
}

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // host, network, service
	SourceId      string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Severity      Severity               `protobuf:"varint,4,opt,name=severity,proto3,enum=alert.v1.Severity" json:"severity,omitempty"`
	Status        AlertStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=alert.v1.AlertStatus" json:"status,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ResolvedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	ResolvedBy    string                 `protobuf:"bytes,10,opt,name=resolved_by,json=resolvedBy,proto3" json:"resolved_by,omitempty"`
	RuleId        string                 `protobuf:"bytes,11,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,12,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_api_proto_alert_v1_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_alert_v1_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_api_proto_alert_v1_alert_proto_rawDescGZIP(), []int{0}
}

func (x *Alert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Alert) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Alert) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Alert) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Alert) GetStatus() AlertStatus {
	if x != nil {
		return x.Status
	}
	return AlertStatus_ALERT_STATUS_UNSPECIFIED
}

func (x *Alert) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Alert) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Alert) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Alert) GetResolvedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResolvedAt
	}
	return nil
}

func (x *Alert) GetResolvedBy() string {
	if x != nil {
		return x.ResolvedBy
	}
	return ""
}

func (x *Alert) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Alert) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ListAlertsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 游标分页 (v2.0+): cursor 来自上次的 next_cursor
	Cursor string `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit  uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 默认 50, 上限 200
	// 老接口兼容 (v1.x): page/size 二选一
	Page uint32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size uint32 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// 过滤
	MinSeverity   Severity    `protobuf:"varint,5,opt,name=min_severity,json=minSeverity,proto3,enum=alert.v1.Severity" json:"min_severity,omitempty"`
	Status        AlertStatus `protobuf:"varint,6,opt,name=status,proto3,enum=alert.v1.AlertStatus" json:"status,omitempty"`
	Source        string      `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsRequest) Reset() {
	*x = ListAlertsRequest{}
	mi := &file_api_proto_alert_v1_alert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsRequest) ProtoMessage() {}

func (x *ListAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_alert_v1_alert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsRequest.ProtoReflect.Descriptor instead.
func (*ListAlertsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_alert_v1_alert_proto_rawDescGZIP(), []int{1}
}

func (x *ListAlertsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListAlertsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAlertsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAlertsRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListAlertsRequest) GetMinSeverity() Severity {
	if x != nil {
		return x.MinSeverity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *ListAlertsRequest) GetStatus() AlertStatus {
	if x != nil {
		return x.Status
	}
	return AlertStatus_ALERT_STATUS_UNSPECIFIED
}

func (x *ListAlertsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ListAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	Total         uint32                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"` // 当前页条目数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsResponse) Reset() {
	*x = ListAlertsResponse{}
	mi := &file_api_proto_alert_v1_alert_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsResponse) ProtoMessage() {}

func (x *ListAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_alert_v1_alert_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsResponse.ProtoReflect.Descriptor instead.
func (*ListAlertsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_alert_v1_alert_proto_rawDescGZIP(), []int{2}
}

func (x *ListAlertsResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *ListAlertsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListAlertsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertRequest) Reset() {
	*x = GetAlertRequest{}
	mi := &file_api_proto_alert_v1_alert_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertRequest) ProtoMessage() {}

func (x *GetAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_alert_v1_alert_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertRequest.ProtoReflect.Descriptor instead.
func (*GetAlertRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_alert_v1_alert_proto_rawDescGZIP(), []int{3}
}

func (x *GetAlertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AckAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckAlertRequest) Reset() {
	*x = AckAlertRequest{}
	mi := &file_api_proto_alert_v1_alert_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckAlertRequest) ProtoMessage() {}

func (x *AckAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_alert_v1_alert_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckAlertRequest.ProtoReflect.Descriptor instead.
func (*AckAlertRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_alert_v1_alert_proto_rawDescGZIP(), []int{4}
}

func (x *AckAlertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AckAlertRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AckAlertRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type ResolveAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAlertRequest) Reset() {
	*x = ResolveAlertRequest{}
	mi := &file_api_proto_alert_v1_alert_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAlertRequest) ProtoMessage() {}

func (x *ResolveAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_alert_v1_alert_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAlertRequest.ProtoReflect.Descriptor instead.
func (*ResolveAlertRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_alert_v1_alert_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveAlertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResolveAlertRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResolveAlertRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type ResolveAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alert         *Alert                 `protobuf:"bytes,1,opt,name=alert,proto3" json:"alert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAlertResponse) Reset() {
	*x = ResolveAlertResponse{}
	mi := &file_api_proto_alert_v1_alert_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAlertResponse) ProtoMessage() {}

func (x *ResolveAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_alert_v1_alert_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAlertResponse.ProtoReflect.Descriptor instead.
func (*ResolveAlertResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_alert_v1_alert_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveAlertResponse) GetAlert() *Alert {
	if x != nil {
		return x.Alert
	}
	return nil
}

var File_api_proto_alert_v1_alert_proto protoreflect.FileDescriptor

const file_api_proto_alert_v1_alert_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/alert/v1/alert.proto\x12\balert.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x04\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12.\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x12.alert.v1.SeverityR\bseverity\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.alert.v1.AlertStatusR\x06status\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vresolved_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"resolvedAt\x12\x1f\n" +
	"\vresolved_by\x18\n" +
	" \x01(\tR\n" +
	"resolvedBy\x12\x17\n" +
	"\arule_id\x18\v \x01(\tR\x06ruleId\x123\n" +
	"\x06labels\x18\f \x03(\v2\x1b.alert.v1.Alert.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe7\x01\n" +
	"\x11ListAlertsRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\rR\x04size\x125\n" +
	"\fmin_severity\x18\x05 \x01(\x0e2\x12.alert.v1.SeverityR\vminSeverity\x12-\n" +
	"\x06status\x18\x06 \x01(\x0e2\x15.alert.v1.AlertStatusR\x06status\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\"t\n" +
	"\x12ListAlertsResponse\x12'\n" +
	"\x06alerts\x18\x01 \x03(\v2\x0f.alert.v1.AlertR\x06alerts\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x14\n" +
	"\x05total\x18\x03 \x01(\rR\x05total\"!\n" +
	"\x0fGetAlertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"N\n" +
	"\x0fAckAlertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\"R\n" +
	"\x13ResolveAlertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\"=\n" +
	"\x14ResolveAlertResponse\x12%\n" +
	"\x05alert\x18\x01 \x01(\v2\x0f.alert.v1.AlertR\x05alert*x\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x01\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x02\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x03\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x04*x\n" +
	"\vAlertStatus\x12\x1c\n" +
	"\x18ALERT_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ALERT_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12ALERT_STATUS_ACKED\x10\x02\x12\x19\n" +
	"\x15ALERT_STATUS_RESOLVED\x10\x032\x96\x02\n" +
	"\fAlertService\x12G\n" +
	"\n" +
	"ListAlerts\x12\x1b.alert.v1.ListAlertsRequest\x1a\x1c.alert.v1.ListAlertsResponse\x126\n" +
	"\bGetAlert\x12\x19.alert.v1.GetAlertRequest\x1a\x0f.alert.v1.Alert\x126\n" +
	"\bAckAlert\x12\x19.alert.v1.AckAlertRequest\x1a\x0f.alert.v1.Alert\x12M\n" +
	"\fResolveAlert\x12\x1d.alert.v1.ResolveAlertRequest\x1a\x1e.alert.v1.ResolveAlertResponseB5Z3network-monitor-platform/api/proto/alert/v1;alertv1b\x06proto3"

var (
	file_api_proto_alert_v1_alert_proto_rawDescOnce sync.Once
	file_api_proto_alert_v1_alert_proto_rawDescData []byte
)

func file_api_proto_alert_v1_alert_proto_rawDescGZIP() []byte {
	file_api_proto_alert_v1_alert_proto_rawDescOnce.Do(func() {
		file_api_proto_alert_v1_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_alert_v1_alert_proto_rawDesc), len(file_api_proto_alert_v1_alert_proto_rawDesc)))
	})
	return file_api_proto_alert_v1_alert_proto_rawDescData
}

var file_api_proto_alert_v1_alert_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_alert_v1_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_alert_v1_alert_proto_goTypes = []any{
	(Severity)(0),                 // 0: alert.v1.Severity
	(AlertStatus)(0),              // 1: alert.v1.AlertStatus
	(*Alert)(nil),                 // 2: alert.v1.Alert
	(*ListAlertsRequest)(nil),     // 3: alert.v1.ListAlertsRequest
	(*ListAlertsResponse)(nil),    // 4: alert.v1.ListAlertsResponse
	(*GetAlertRequest)(nil),       // 5: alert.v1.GetAlertRequest
	(*AckAlertRequest)(nil),       // 6: alert.v1.AckAlertRequest
	(*ResolveAlertRequest)(nil),   // 7: alert.v1.ResolveAlertRequest
	(*ResolveAlertResponse)(nil),  // 8: alert.v1.ResolveAlertResponse
	nil,                           // 9: alert.v1.Alert.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_api_proto_alert_v1_alert_proto_depIdxs = []int32{
	0,  // 0: alert.v1.Alert.severity:type_name -> alert.v1.Severity
	1,  // 1: alert.v1.Alert.status:type_name -> alert.v1.AlertStatus
	10, // 2: alert.v1.Alert.created_at:type_name -> google.protobuf.Timestamp
	10, // 3: alert.v1.Alert.resolved_at:type_name -> google.protobuf.Timestamp
	9,  // 4: alert.v1.Alert.labels:type_name -> alert.v1.Alert.LabelsEntry
	0,  // 5: alert.v1.ListAlertsRequest.min_severity:type_name -> alert.v1.Severity
	1,  // 6: alert.v1.ListAlertsRequest.status:type_name -> alert.v1.AlertStatus
	2,  // 7: alert.v1.ListAlertsResponse.alerts:type_name -> alert.v1.Alert
	2,  // 8: alert.v1.ResolveAlertResponse.alert:type_name -> alert.v1.Alert
	3,  // 9: alert.v1.AlertService.ListAlerts:input_type -> alert.v1.ListAlertsRequest
	5,  // 10: alert.v1.AlertService.GetAlert:input_type -> alert.v1.GetAlertRequest
	6,  // 11: alert.v1.AlertService.AckAlert:input_type -> alert.v1.AckAlertRequest
	7,  // 12: alert.v1.AlertService.ResolveAlert:input_type -> alert.v1.ResolveAlertRequest
	4,  // 13: alert.v1.AlertService.ListAlerts:output_type -> alert.v1.ListAlertsResponse
	2,  // 14: alert.v1.AlertService.GetAlert:output_type -> alert.v1.Alert
	2,  // 15: alert.v1.AlertService.AckAlert:output_type -> alert.v1.Alert
	8,  // 16: alert.v1.AlertService.ResolveAlert:output_type -> alert.v1.ResolveAlertResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_alert_v1_alert_proto_init() }
func file_api_proto_alert_v1_alert_proto_init() {
	if File_api_proto_alert_v1_alert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_alert_v1_alert_proto_rawDesc), len(file_api_proto_alert_v1_alert_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_alert_v1_alert_proto_goTypes,
		DependencyIndexes: file_api_proto_alert_v1_alert_proto_depIdxs,
		EnumInfos:         file_api_proto_alert_v1_alert_proto_enumTypes,
		MessageInfos:      file_api_proto_alert_v1_alert_proto_msgTypes,
	}.Build()
	File_api_proto_alert_v1_alert_proto = out.File
	file_api_proto_alert_v1_alert_proto_goTypes = nil
	file_api_proto_alert_v1_alert_proto_depIdxs = nil
}
